language: ruby
rvm: 2.2.1
env: RAILS_ENV=test
script:
  - bundle exec rspec
addons:
  postgresql: "9.3.10"
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database test_travis;' -U postgres
  - bundle exec rake db:migrate
install: bundle install --jobs=3 --retry=3
