language: ruby
rvm:
  - 2.2.1
env:
  - DB=postgres
addons:
  postgresql: "9.4"

services:
  - postgresql

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database test_travis;' -U postgres
  - RAILS_ENV=test bundle exec rake db:create
