development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: swest
  password: 12108484

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: swest
  password: 12108484
